version: '3.1'
networks:
  network1:        
  network2:

services:
  proxy:
    build: ./proxy
      #context: ./proxy
      #dockerfile: DockerfileProxy
    container_name: proxyContainer
    networks:
    - network1
    ports:
    - "443:443"
    depends_on:
      - backend
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=8080
  backend:
    build: ./backend
      #context: ./backend
      #dockerfile: DockerfileBackend
    container_name: backendContainer
    links:
      - database
    depends_on:
      - database
    networks:
      - network1
      - network2
  database:
    build: ./database
      #context: ./database
      #dockerfile: DockerfileDatabase
    container_name: databaseContainer
    networks:
    - network2
    command: --default-authentication-plugin=mysql_native_password